### ISSUE TITLE
Implement a DDF schema and the validation backend for provider creation

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-nsxt#14]
In order to be able to add a provider through the UI, we need to implement the `self.params_for_create` and `self.verify_credentials` methods on the `NetworkManager` or the `ManagerMixin`. I think I can do most of the heavy lifting here, but I'd need some help with the stateless validation (not requiring DB record creation) and some info about how the provider form should look like (what fields, validation, etc).

@agrare @gubbe505 
@miq-bot add_label help wanted

**Comment by gubbe505** [comment]
Here is the Provider page in the old Ruby style I made for Hammer/Ivanchuk.

![image](https://user-images.githubusercontent.com/57907607/92217903-9d511d80-ee98-11ea-8b5e-6bbaeb83e86d.png)
